apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
- ../../base

patches:
- path: env-patch.yaml

# Prefer the images transformer so CI can "edit set image" here
images:
- name: gitlab-registry.empa.ch/openbis-tools/ilog
  newName: gitlab-registry.empa.ch/openbis-tools/ilog
  newTag: 398d14e0653e314a136140f2ff4f6db3bd2d79ec
