apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: default
resources:
- ../../base

patches:
- path: env-patch.yaml

# Prefer the images transformer so CI can "edit set image" here
images:
- name: gitlab-registry.empa.ch/openbis-tools/ilog
  newName: gitlab-registry.empa.ch/openbis-tools/ilog
  newTag: 05390be159409829984d26793e4eb56943307a50
