apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
namespace: default
resources:
- ../../base

patches:
- path: env-patch.yaml

# Prefer the images transformer so CI can "edit set image" here
images:
- name: gitlab-registry.empa.ch/openbis-tools/ilog
  newName: gitlab-registry.empa.ch/openbis-tools/ilog
  newTag: 088caa980af8160b6ceca6f8a620db79439706d1
