---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-secret
  namespace: ilog
spec:
  encryptedData:
    .dockerconfigjson: AgBNcmG5i53pFqnjD2k6ej3fJYugxvwQ/xzif25SOvX6JqwjlpFhHEmuODB8iKjT6W0kYHVUEEM1yTovoIKDBvC6Iy9gUGTCAQhGgommpvt9UPZ+87hpbEEJOSmmd0CVY4mYmP33V4TxNCgIeJb1gqNHsxet9k/Cmrm7u9HMQu9Fm6UynZZzMgyns3P7Dx4NsCSFkWN4Az9A94deGvq8tCf2yfs2YHHh8dN5D7VaOh+OpY5QEiJ8tjT4DXhPg4BK1/ytLhbLZpOiHNWY/yC6cZ7LM0azb2kfJNCvvyZjUx84Dcw9C8Y+5WdLwGN4AzedyCrxVs6vMYKl/57YDS1Ao4JyNd6KDta2WMYVY0zcsH4XVyQNqxFUcNN8bG7REfo1qelK8uSJLaV2htrmCP/GQLcPPRjuEvo+J5yVuNHcaVFhITY37UMaI2sTcgGivbKwiAcrZow0tQYqfATiMUxh83G04Jv4L5Z3X1soQ/Z0aQzFB1o/kv0jllcOZB3Tgs5hPjBdP2ogfUUrBc0YwVm/6ExCFMRdyBVkka9zh67ZWojSf22a7VvAMSIKMR0Zxn6V2pFA7fFfPhO7xrYji5JU64PyQXcguaRbjUXwJ91UIcElOcPcqJHPQBRGzgJyZFijxUH9BlogprH4GVAQjOH1PaZ0ezKbCxnyR/TNlBmtVIXOF5vPR7ChK68sE65kA2dgIRkW8PjqK7alK9bN2gLuMnwARxrNmpU/MBf4gN+gEs03oq1EWz23FgYgNtD8xGo6LUZXf1gTeFnee3SAFvEJMr/K4WkTokokGujpQ1q3l4ERvUEtRhs/+72QnNcp7YrR2rhXajw7Ez2FyEC6JV0qMpBgsASJTeTzOAZL7bCDbIGYf01q7PEJXfN7GnoCAtEeXwT3b1W6lhapWnrXVhVvOEQ=
  template:
    metadata:
      name: gitlab-registry-secret
      namespace: ilog
    type: kubernetes.io/dockerconfigjson