


variables:
  DOCKER_IMAGE_SHA_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA # CI_COMMIT_SHA is the commit hash => a1b2c3d4
  DOCKER_IMAGE_BRANCH_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG # CI_COMMIT_REF_SLUG is the branch name
  DOCKER_IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest


stages:
  - build
  - push
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - master
  tags:
    - dind
  rules:
    - changes: 
      - Dockerfile
      - Caddyfile
      - src/**/*
      - package.json
      - "*.js"
      - "*.ts"




deploy:
  before_script:
    - apk add --no-cache git curl ca-certificates
    - curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.7.1/kustomize_v5.7.1_linux_amd64.tar.gz | tar xz
    - mv kustomize /usr/local/bin/
    - kustomize version && git --version
  stage: deploy
  image: alpine:3.20
  script:
    - echo "Pinning dev image to $DOCKER_IMAGE_SHA_TAG"
    - cd k8s/overlays/dev
    # Left side must match the *canonical image name* as it appears in manifests
    - kustomize edit set image gitlab-registry.empa.ch/openbis-tools/ilog=$DOCKER_IMAGE_SHA_TAG
    - git config --global user.email "ci-bot@gitlab.empa.ch"
    - git config --global user.name "CI Bot"
    - git add kustomization.yaml
    - git commit -m "Pin ilog to to $DOCKER_IMAGE_SHA_TAG [ci skip]" 
    - git push "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" HEAD:$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'