version: "3.7"



services:
  # openbis:
  #   container_name: openbis-ingress
  #   image: openbis/openbis-local:latest
  #   ports:
  #     - 443:443 # main port
  #   depends_on:
  #     - app
  #   environment:
  #     - OPENBIS_HOST=host.docker.internal
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  caddy:
    image: caddy:2
    ports:
      - "8080:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    env_file: 
      - .env
    depends_on:
      - openbis-app
    networks:
      - openbis-network

  db:
    container_name: openbis-db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${OPENBIS_DB_ADMIN_PASS}
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - openbis-db-data:/var/lib/postgresql/data
    env_file: 
      - .env
    networks:
      - openbis-network

  openbis-app:
    container_name: ${OPENBIS_APP_NAME}

    build:
      context: openbis
      dockerfile: Dockerfile
      args:
        - OPENBIS_VERSION=6.6.0
    depends_on:
      - db
    volumes:
      - openbis-app-data:/data
      - openbis-app-etc:/etc/openbis
      - openbis-app-logs:/var/log/openbis
    # ports:
    #   - ${OPENBIS_AS_PORT}:8080 # main port for AS
    #   - ${OPENBIS_DSS_PORT}:8081 # main port for DSS
    #   - ${OPENBIS_AFS_PORT}:8085 # main port for AFS
    env_file: 
      - .env
    networks:
      - openbis-network
    
  # ilog:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/workspace:cached
  #   depends_on:
  #     - app
  #   env_file: 
  #     - .env
  #   networks:
  #     - openbis-network

volumes:
  openbis-db-data:
    name: "openbis-db-data"
  openbis-app-data:
    name: "openbis-app-data"
  openbis-app-etc:
    name: "openbis-app-etc"
  openbis-app-logs:
    name: "openbis-app-logs"

networks:
  openbis-network:
    name: "openbis-network"
