---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-credentials
  namespace: ilog
spec:
  encryptedData:
    .dockerconfig.json: AgBR3ZBd99bdxB3d9LEax2JLIIcDcnojRbHiDVZQAb2rkXDY8rvS4SsXVLkNzL7sHHe5qLXLSp3i/vghvDoPwY3XonWRXnpXrQr6beHDVMLuN1kxoMOJGBLlMDEoZwbYYkHQxHtOkTR1dJlCTh3ar2qmOdoUbxbWv4rDXoVhsni7dChVWNwXl9JQFfNtKH4BADYS5QkaS74TT4V/bz2XBeg1x9ODi97q8C7VXqSvWOCC8jAoPPq/0N47k+t1TzlHPNOVNw3SjlfvpyuMOTIxxY3bch9Xnv++uMZYkDhc1FwlmXRQ7T1priWJw55ETItRr45+TRwS/CP/rdAQzmVKhVASeV8mpbIZC7yq8hYWVl4ULl3e2xXzm4SFwE//Ir+/Se/hDGJMhTfnns7F/szXTYaCAeWa9dDq55/cxYSeorJdOIhKxjcBB1SYkYYjN5ZntdowhZDeGCiqz56yg2cblpsvHJU3WXM/nSlq31c8kwNeYHM51sJYaevDmc3iqrLyn+oqPRrTi4guW4KCehJrDzeezLjK61vAvHxuzIu1BnwfeSYPFKmuWpnCMYlglLsev83PJ5dITxoRwNHDaxuARWRmgtWDoNCaqNuXXbkEU4vwQ3SeYL2GkpAayn1sGf0E9ye5SDhuAVY7Q52ztrITwa/WERNNAtnRyTBQkOO9qAQtT8SrfCsLKXrIyEi9A3HcUzD53/9A2J1YSnDUDLN/PcaWHkPOZqGRmBIwisRMwtJ0BiMYvV7gd0Nsjn/AS5tFRlxg5gRsHVXKV5UCKNvFeg8p/6mEA10ZS4DlvD/T/NKCKMLxXeW0yhfivHqQwMk/1nH6yJZ9eTOQWbrVPfQ232rXH7iKLr0G0iuKGpc53rgpiwjPlPRiIuaEwYSlRcx92Hf0dPbsN6jS+iwr4x3WNkpZL+3cd6TLCZpV42SSTVEKBR/qJNsOQl1YXQpwYXLslHK7ykCTjw3Flp8IGFdAmBtBxGdGbrz9i1e+hGe97HUUoQzSsWVIJCurPCqe9ik9PjNn3+1ZSpQwQ/u2e3K9dx6b/xsX5rYTtiIP8O6HaDUTy4LklOJvDPeO71Bu5ogp1+Rf1/uPvcfpePv7fT9itiGPLxyIRKuXSZk7OOw9marPXz1qo8OAHejfeJlsCtNohu3UYOWjQsvAwg7HIrNXWrOqsCz69qPwN5AXcwHwhA0neEtI3DEmblrAz7MgaIgYBSK0sIF+WS9y9idZ/3g3t65odT+fIGNpLDllUVAqdKd5Ra3KlXUdIlUpHxxoYHCn5L5b1B9Q73ll4z99P0qWKkHgehfFQQU/
  template:
    metadata:
      name: gitlab-registry-credentials
      namespace: ilog
