version: '3.2.1'

tasks:
  start_openbis:
    cmds:
      - docker compose up -d
    desc: Start openBIS

  dev:
    cmds:
      - npm run dev
    desc: Start the development server
    deps:
      - start_openbis
  
  test:
    cmds:
      - npm run test 
    desc: Run the tests
    deps:
      - start_openbis