apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
namespace: default
resources:
- ../../base

# Prefer the images transformer so CI can "edit set image" here
images:
- name: gitlab-registry.empa.ch/openbis-tools/ilog
  newName: gitlab-registry.empa.ch/openbis-tools/ilog
  newTag: c5df57cc498c5acc63b18a615a2048455d3ac580
