apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ilog-dev
resources:
- ../../base
- ./sealed-secrets.yaml

patches:
- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: ilog-dev.empa.ch
    - op: replace
      path: /spec/tls/0/hosts/0
      value: ilog-dev.empa.ch
  target:
    kind: Ingress
    name: ilog

configMapGenerator:
- behavior: replace
  literals:
  - OPENBIS_URL=https://openbis-empa-dev205.ethz.ch
  name: ilog-env

# Prefer the images transformer so CI can "edit set image" here
images:
- digest: sha256:6000c776e9fdea73874b3c1e79740690561c66c1198533656c5276231314ffd3
  name: gitlab-registry.empa.ch/openbis-tools/ilog
  newName: gitlab-registry.empa.ch/openbis-tools/ilog
