---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-secret
  namespace: ilog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBjwsMMJRUU4Y7rERNegDmkwNj40jGhdYlA//o6RAUcsxC3+/HfZ8RBLDmqpsAkZRQ4ogEIYRFJG3BIOqip3P6r7owLtsV1wMYAqVVveYueOSz6EvBCzswYfVBe5+jeh9MT5VXFlpJsx7+RP5TlDvVHtBROKh6rUOn2pt2IkgGtd6n9scTI3AM8yvPB7FJ2T8LufkwLd2Qx0Rzqn9g2mrbbc0AJG89upqysPlTUr/p9ooCJ9n/R7pyaL3OhCrpQBC/ybT41kk8V7pwJMDLuILuw2iTw0YND5JhKYQtiJgkfkxnB4cv5lz3k98wj+gq+hr0xS2YIszdrYBJOn5w68z3zOHKbaYvZk1mDQqWyGMluCYdLJtwHfdATV/f3hLpZq94bq9NGWJt3NhUE3l909gjWi4HQYpfiraw3V0NZOnOLHfAAQFVT9nO5Xxl9UKIlUuoqybIcE00YErzGPitqMK5S6TrCduIwHFLnubhCpDF/jEYHkaLW+IvEh+TvJ+ngnxmEH4CM/hedQ0o1xA4QvADsY38LrRs8ZcWKtT9mpcczyDhNmm8Jtnarzt/VO+xz077e+nGGblYP01vWQHNnWg+w0NkG35DbKxAEsJtSrdY9WKZg7ieEQuIL1ErbvQpXdApIfyMdSkRnLFPF1s2CXSMVon605n7zg3Bu+OyO/YAVRrZ1f0JzeTtQK6U4xCXluCT432XVbcwz+dxjyfXhGAvxtaSzwNRSmnszj5uCGU9M3ZR4oblDyqtr4Dy5dfxV8Mx62XfjEz+KLMZLcfzeZ/dXW/Rf4uxrQkrHXJoWuY6E01oR6iMMA3x+FP+7h9cwTr0AngA6NG54rxKv3jQmqtffv8/z2Xa1SXHIfa+MPMklUEVGorBGR2F0FpMIKd33Sds+rmxveyGZIN/TXQyPRB0=
  template:
    metadata:
      name: gitlab-registry-secret
      namespace: ilog-dev
    type: kubernetes.io/dockerconfigjson