---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-credentials
  namespace: ilog-dev
spec:
  encryptedData:
    .dockerconfig.json: AgBXZbuIZsPWTD6z6nmscA3KSrvwqCY55BDqHWFfgQdaPWm2T5ehB9iSo/KalELuKSOBmkBLSKBsTsK6P7cKuFvf68Bx18P8py+0720c0dcOjB3CwcECF0dAnTWXfYUVcb/8gv5Slg7hBv0X1eEs6jDl/fkqGv1kV5xHwz5hme4DkaEVByop++YHOUcDAP6ITbu5OAVbVpdnrFvpGaeJqMpRohweBXEx2RJcjObVO54UR5CAu9pBer9GEA7erYhzeFuzY6vsRm0KstvaiTw+R/e1c1R2nnTV3u3kXCV5H9mf9zPLzq8G8dJ4ZAZGIArWmIzlcAz2SA3bLwJ8o9iUKTss52ZkgzCVgsAcN/tdUwyy+tYctD02hDsFbTeF9AhbDy0pAUBg6LxmlF+s8VGpcsUOacbopQBpmdKkR3k3ZCLLjHrJAwgqbxG79VmLmvMthlRE2mxmqWHCZ5RDtHGIFM83mtCsTtQZUVLbY5D42V5aOj99FoqgfZ9j3izQJd7A+63GKqH47QilUxJro4+yUu2V1oXzP5eVIFra1q+bjsfBn9Gk79NpaGQbrqHfw3geJ43yUT4wACDpgD25JIm2vemptforRPxFnFi9FFZmYTLoKOqVhrpSR1zVhOY5DYO73o/up3reVR58Ia1ZCnvkjNiwlRw52jK1eBiQWl7MmxXKpToXn761lWIPyxU8EmBrovo7avUFVV81bmDTOp6EdLPqjvwOZT63qOi+4flKHMs9ECN1c7sjDiNvqfvJFsi9BzXr5tniktbrb60HqJHOqJX5MJ25AqHbHZT6BzxYcnOUYQ7Dc7Y/1sD2Sv+LH1NkULHo/QQ4eWgtiRGnHuyFN9zIRrskQFGf8ZjWLUsY+uM+5kxIIldUqNcC0WGKQsWVMt4c2HRTay3qWzgzdTQsJnIJFd/Gq43ZUDlVEbnNh3TDRBxsRgARfs87Xb1NJeL7xhsZ+9xWA1wxpBL70RzzQe5E8RYm8ETwcknQA9zFT+nm0e5qIgKXjzFo4253tWCtTqVrIMPhdQm1s+aSWcrv2gIZbK2e+5pEmkrJexAqDwc04cN+QZgn4zWkR7F2IwdL2IRECwvxxJ9nOK1GvSOE6s9pvjI8wUmHvLIUIbB0Ny+Hb8TMFF1UApkYnsG/3gPuHXIjn/O6VgQ1XSgyxmjJoH1I4qJWujm3a2MGqPDXvlAuJjUTe1UGsvoGbwl1axFcBKbl8wh4VC/DR1m5aeCyOPEgcy859XvcPce8MuAi7mv7eDGaV5pW7krQTDHhfE9YUULpGL5t+frWtA2tfipkAE0vPK1oI+N9
  template:
    metadata:
      name: gitlab-registry-credentials
      namespace: ilog-dev
