apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilog
  namespace: ilog
  annotations:
    spec.ingressClassName: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
      - host: ilog.empa.ch
        http:
          paths:
            - backend:
                service:
                  name: ilog
                  port:
                    number: 80
              path: /
              pathType: Prefix
  tls:
      - hosts:
          - ilog.empa.ch