apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ilog
resources:
  - deploy.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml

configMapGenerator:
  - name: ilog-env
    literals:
      - OPENBIS_URL=https://openbis-empa-lab205.ethz.ch