apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ilog
  template:
    metadata:
      labels:
        app: ilog
    spec:
      containers:
        - name: ilog
          image: gitlab-registry.empa.ch/openbis-tools/ilog
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ilog
  namespace: default
spec:
  selector:
    app: ilog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilog
  namespace: default
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
    - http:
        paths:
          - path: /ilog
            pathType: Prefix
            backend:
              service:
                name: ilog
                port:
                  number: 80
