import openbis from "@openbis/openbis.esm";
import {
  parseElnSettingsProperties,
  updateElnSettings,
  newTypeSettings,
} from "../shared/common";
import {
  PropertyTypesSchema,
  ObjectTypeDefinition,
  StructuredCreations
} from "./commonType";
import { convertPropertyTypeToCreation, LocalPropertyType } from "../propertyType/commonPropertyType";
import { getPropertyTypeId } from "../propertyType/commonPropertyType";

/**
 * Update ELN settings to automatically enable an object type upon creation.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param typeName - The name of the object type to enable.
 */
export async function createObjectTypeSettingsDefinition(
  api: openbis.OpenBISJavaScriptFacade,
  typeName: string
): Promise<void> {
  // Parse existing ELN settings properties
  var properties = await parseElnSettingsProperties(api);
  // Expand the settings with the appropriate properties for enabling the new type
  properties.sampleTypeDefinitionsExtension = {
    ...properties.sampleTypeDefinitionsExtension,
    [typeName]: newTypeSettings,
  };
  // Update the ELN settings with the new properties
  await updateElnSettings(api, properties);
}

/**
 * Delete object type from ELN settings upon its deletion.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param typeName - The name of the object type to disable.
 */
export async function deleteObjectTypeSettingsDefinition(
  api: openbis.OpenBISJavaScriptFacade,
  typeName: string
): Promise<void> {
  // Parse existing ELN settings properties
  var properties = await parseElnSettingsProperties(api);
  // Remove the specified object type from the settings
  delete properties.sampleTypeDefinitionsExtension[typeName];
  // Update the ELN settings with the modified properties
  await updateElnSettings(api, properties);
}

/**
 * Convert an object schema to property creations.
 * @param schema - The object schema to convert.
 * @returns An array of PropertyTypeCreation objects.
 */
function convertPropertyTypesSchemaToPropertyCreations(
  schema: PropertyTypesSchema
): openbis.PropertyTypeCreation[] {
  // Convert each property in the schema to a PropertyTypeCreation
  const creations = Object.entries(schema)
    .flatMap(([group, properties]) => {
      return properties.map((prop) =>
        prop ? convertPropertyTypeToCreation(prop) : null
      );
    })
    .filter((el) => el !== null);
  return creations ?? [];
}

/**
 * Convert an object schema to assignment creations.
 * @param schema - The object schema to convert.
 * @returns An array of PropertyAssignmentCreation objects.
 */
function convertPropertyTypesSchemaToAssignmentCreations(
  schema: PropertyTypesSchema
): openbis.PropertyAssignmentCreation[] {
  let index = 0;
  // Convert each property in the schema to a PropertyAssignmentCreation
  const creations = Object.entries(schema)
    .flatMap(([section, properties]) => {
      return properties.map((prop) => {
        const creation = new openbis.PropertyAssignmentCreation();
        creation.setSection(section);
        creation.setPropertyTypeId(getPropertyTypeId(prop));
        creation.setOrdinal(++index);
        return creation;
      });
    })
    .filter((el) => el.getPropertyTypeId() !== null);
  return creations;
}

/**
 * Convert an object type definition to structured creations.
 * @param objectDefinition - The object type definition to convert.
 * @returns A StructuredCreations object containing property and object type creations.
 */
export function convertObjectTypeDefinitionToOperations(
  objectDefinition: ObjectTypeDefinition
): StructuredCreations {
  // Create property creations
  const propertyTypeCreations = convertPropertyTypesSchemaToPropertyCreations(
    objectDefinition.propertyTypes
  );
  // For each creation, create the assignments
  const assignmentCreations = convertPropertyTypesSchemaToAssignmentCreations(
    objectDefinition.propertyTypes
  );
  // Create the object type
  const sampleTypeCreation = new openbis.SampleTypeCreation();
  sampleTypeCreation.setCode(objectDefinition.code);
  sampleTypeCreation.setAutoGeneratedCode(true);
  sampleTypeCreation.setGeneratedCodePrefix(
    objectDefinition.generatedCodePrefix.length > 0 ? objectDefinition.generatedCodePrefix : objectDefinition.code.slice(0, 5)
  );
  sampleTypeCreation.setPropertyAssignments(assignmentCreations);
  sampleTypeCreation.setDescription(objectDefinition.description);
  sampleTypeCreation.setListable(true);
  // Return the structured creations
  const all = {
    propertyTypeCreations: propertyTypeCreations,
    objectTypeCreations: [sampleTypeCreation],
  };
  return all;
}

/**
 * Convert structured creations to operations.
 * @param creations - The structured creations to convert.
 * @returns An array of IOperation objects.
 */
export function convertCreationsToOperations(
  creations: StructuredCreations
): openbis.IOperation[] {
  return [
    new openbis.CreatePropertyTypesOperation(creations.propertyTypeCreations),
    new openbis.CreateSampleTypesOperation(creations.objectTypeCreations),
  ];
}



/**
 * Convert an object schema to assignment updates.
 * @param schema - The object schema to convert.
 * @param existingPropertyTypes - The existing property assignments to compare against.
 * @returns An array of PropertyAssignmentUpdate objects.
 */
export function convertPropertyTypesSchemaToUpdateOperations(
  schema: PropertyTypesSchema,
  existingPropertyTypes: LocalPropertyType[]
): openbis.IOperation[] {
  // Convert each property in the schema to a PropertyAssignmentUpdate
  const updates = Object.entries(schema)
    .flatMap(([section, properties]) => {
      return properties.map((prop: any, index) => {
        const creation = convertPropertyTypeToCreation(prop);
        // Compare with existing property
        const existingPropertyType = existingPropertyTypes.find(
          (assignment) => assignment.code == getPropertyTypeId(prop)
        );

        if ( !existingPropertyType ||
          (existingPropertyType.label === prop.label &&
          existingPropertyType.description === prop.description &&
          existingPropertyType.dataType === prop.dataType)
        ) {
          // No changes, skip update
          return null;
        }

        const update = new openbis.PropertyTypeUpdate();
        // update.setSchema(section);
        update.setTypeId(getPropertyTypeId(prop));
        // update.setOrdinal(index + 1);
        update.setLabel(prop.label);
        update.setDescription(prop.description);
        update.convertToDataType(prop.dataType);
        return update;
      });
    })
    .filter((el) => el !== null);
  
  const operations = new openbis.UpdatePropertyTypesOperation(updates);

  return [operations];
}


/**
 * Convert an object type definition to update operations.
 * @param objectDefinition - The object type definition to convert.
 * @param existingObjectTypes - The existing object types to compare against.
 * @returns An array of IOperation objects.
 */
export function convertObjectTypeDefinitionToUpdateOperations(
  objectDefinition: ObjectTypeDefinition,
  existingObjectTypes: openbis.SampleType[]
): openbis.IOperation[] {
  const existingObjectType = existingObjectTypes.find(
    (type) => type.getCode() === objectDefinition.code
  );

  if (!existingObjectType) {
    // If the object type does not exist, return an empty array
    return [];
  }

  const update = new openbis.SampleTypeUpdate();
  update.setTypeId(existingObjectType.getPermId());
  update.setDescription(objectDefinition.description);
  update.setAutoGeneratedCode(true);
  update.setGeneratedCodePrefix(
    objectDefinition.generatedCodePrefix.length > 0 ? objectDefinition.generatedCodePrefix : objectDefinition.code.slice(0, 5)
  );
  update.setListable(true);

  const assignmentUpdates = new openbis.PropertyAssignmentListUpdateValue();
  assignmentUpdates.set(convertPropertyTypesSchemaToAssignmentCreations(objectDefinition.propertyTypes));
  update.setPropertyAssignmentActions(assignmentUpdates.getActions());

  return [new openbis.UpdateSampleTypesOperation([update])];
}