import openbis from "@openbis/openbis.esm";
import {
  parseElnSettingsProperties,
  updateElnSettings,
  newTypeSettings,
} from "../shared/common";
import {
  ObjectSchema,
  ObjectTypeDefinition,
  StructuredCreations
} from "./commonType";
import { convertPropertyTypeToCreation } from "../propertyType/commonPropertyType";
import { getPropertyTypeId } from "../propertyType/commonPropertyType";

/**
 * Update ELN settings to automatically enable an object type upon creation.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param typeName - The name of the object type to enable.
 */
export async function createObjectTypeSettingsDefinition(
  api: openbis.OpenBISJavaScriptFacade,
  typeName: string
): Promise<void> {
  // Parse existing ELN settings properties
  var properties = await parseElnSettingsProperties(api);
  // Expand the settings with the appropriate properties for enabling the new type
  properties.sampleTypeDefinitionsExtension = {
    ...properties.sampleTypeDefinitionsExtension,
    [typeName]: newTypeSettings,
  };
  // Update the ELN settings with the new properties
  await updateElnSettings(api, properties);
}

/**
 * Delete object type from ELN settings upon its deletion.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param typeName - The name of the object type to disable.
 */
export async function deleteObjectTypeSettingsDefinition(
  api: openbis.OpenBISJavaScriptFacade,
  typeName: string
): Promise<void> {
  // Parse existing ELN settings properties
  var properties = await parseElnSettingsProperties(api);
  // Remove the specified object type from the settings
  delete properties.sampleTypeDefinitionsExtension[typeName];
  // Update the ELN settings with the modified properties
  await updateElnSettings(api, properties);
}

/**
 * Convert an object schema to property creations.
 * @param schema - The object schema to convert.
 * @returns An array of PropertyTypeCreation objects.
 */
function convertObjectSchemaToPropertyCreations(
  schema: ObjectSchema
): openbis.PropertyTypeCreation[] {
  // Convert each property in the schema to a PropertyTypeCreation
  const creations = Object.entries(schema)
    .flatMap(([group, properties]) => {
      return properties.map((prop) =>
        prop ? convertPropertyTypeToCreation(prop) : null
      );
    })
    .filter((el) => el !== null);
  return creations ?? [];
}

/**
 * Convert an object schema to assignment creations.
 * @param schema - The object schema to convert.
 * @returns An array of PropertyAssignmentCreation objects.
 */
function convertObjectSchemaToAssignmentCreations(
  schema: ObjectSchema
): openbis.PropertyAssignmentCreation[] {
  // Convert each property in the schema to a PropertyAssignmentCreation
  const creations = Object.entries(schema)
    .flatMap(([section, properties]) => {
      return properties.map((prop, index) => {
        const creation = new openbis.PropertyAssignmentCreation();
        creation.setSection(section);
        creation.setPropertyTypeId(getPropertyTypeId(prop));
        creation.setOrdinal(index + 1);
        return creation;
      });
    })
    .filter((el) => el.getPropertyTypeId() !== null);
  return creations;
}

/**
 * Convert an object type definition to structured creations.
 * @param objectDefinition - The object type definition to convert.
 * @returns A StructuredCreations object containing property and object type creations.
 */
export function convertObjectTypeDefinitionToOperations(
  objectDefinition: ObjectTypeDefinition
): StructuredCreations {
  // Create property creations
  const propertyTypeCreations = convertObjectSchemaToPropertyCreations(
    objectDefinition.propertyAssignments
  );
  // For each creation, create the assignments
  const assignmentCreations = convertObjectSchemaToAssignmentCreations(
    objectDefinition.propertyAssignments
  );
  // Create the object type
  const sampleTypeCreation = new openbis.SampleTypeCreation();
  sampleTypeCreation.setCode(objectDefinition.code);
  sampleTypeCreation.setAutoGeneratedCode(true);
  sampleTypeCreation.setGeneratedCodePrefix(
    objectDefinition.prefix.length > 0 ? objectDefinition.prefix : objectDefinition.code.slice(0, 5)
  );
  sampleTypeCreation.setPropertyAssignments(assignmentCreations);
  sampleTypeCreation.setDescription(objectDefinition.description);
  sampleTypeCreation.setListable(true);
  // Return the structured creations
  const all = {
    propertyTypeCreations: propertyTypeCreations,
    objectTypeCreations: [sampleTypeCreation],
  };
  return all;
}

/**
 * Convert structured creations to operations.
 * @param creations - The structured creations to convert.
 * @returns An array of IOperation objects.
 */
export function convertCreationsToOperations(
  creations: StructuredCreations
): openbis.IOperation[] {
  return [
    new openbis.CreatePropertyTypesOperation(creations.propertyTypeCreations),
    new openbis.CreateSampleTypesOperation(creations.objectTypeCreations),
  ];
}
