import openbis from '@openbis/openbis.esm';
import { iLogID } from '../shared/common';

export async function createIlogIdentifier(
  api: openbis.OpenBISJavaScriptFacade,
): Promise<void> {
  // Initialize the iLog property type identifier
  const sc = new openbis.PropertyTypeSearchCriteria();
  sc.withCode().thatEquals(iLogID);
  const fo = new openbis.PropertyTypeFetchOptions();
  const result = await api.searchPropertyTypes(sc, fo);
  if (result.getTotalCount() == 0) {
    const newProp = new openbis.PropertyTypeCreation();
    newProp.setCode(iLogID);
    newProp.setLabel(iLogID);
    newProp.setDataType('BOOLEAN');
    newProp.setDescription('This is the iLog identifier.');
    await api.createPropertyTypes([newProp]);
    console.log('iLog property type initialized.');
  }
  else {
    console.log('iLog property type already exists.', result);
  }
}

export async function getTypes(
  api: openbis.OpenBISJavaScriptFacade,
  search: string = '',
): Promise<openbis.SampleType[]> {
  const sc = new openbis.SampleTypeSearchCriteria();
  sc.withCode().thatStartsWith(search.toUpperCase());
  const fo = new openbis.SampleTypeFetchOptions();
  fo.withPropertyAssignments();
  const result = await api.searchSampleTypes(sc, fo);
  const iLogTypes = result.getObjects().filter(
    type => type.getPropertyAssignments().some(
      propAsgn => propAsgn.getPermId().getPropertyTypeId() == iLogID
    )
  );
  return iLogTypes;
}

export async function createType(
  api: openbis.OpenBISJavaScriptFacade,
  code: string,
  prefix: string,
  description: string,
): Promise<void> {
  // assign iLog identifier property
  const newPropAsgn = new openbis.PropertyAssignmentCreation();
  newPropAsgn.setPropertyTypeId(new openbis.PropertyTypePermId(iLogID));
  newPropAsgn.setMandatory(true);
  newPropAsgn.setManagedInternally(true);
  newPropAsgn.setSection('General');
  // create type
  const newType = new openbis.SampleTypeCreation();
  newType.setCode(code);
  newType.setAutoGeneratedCode(true);
  newType.setGeneratedCodePrefix(prefix);
  newType.setDescription(description);
  newType.setPropertyAssignments([newPropAsgn]);
  await api.createSampleTypes([newType]);
}

export async function deleteType(
  api: openbis.OpenBISJavaScriptFacade,
  sampleTypeId: openbis.IEntityTypeId,
): Promise<void> {
  const stdo = new openbis.SampleTypeDeletionOptions();
  stdo.setReason('Type no longer needed.');
  await api.deleteSampleTypes([sampleTypeId], stdo);
}
