import openbis from "@openbis/openbis.esm";
import { iLogID } from "../shared/common";
import { componentCollectionID, instrumentCollectionID } from "../shared/environment";


/**
 * Get all objects from the iLog inventory Equipment collection.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param labID - The lab ID to search in.
 * @returns A promise that resolves to an array of Sample objects.
 */
export async function getObjects(
  api: openbis.OpenBISJavaScriptFacade,
  labID: string,
): Promise<openbis.Sample[]> {
  const sc = new openbis.SampleSearchCriteria();
  sc.withSpace().withCode().thatEquals(labID);
  sc.withProject().withCode().thatEquals(iLogID);
  const experimentCriteria = sc.withSubcriteria().withOrOperator();
  experimentCriteria.withExperiment().withCode().thatEquals(componentCollectionID);
  experimentCriteria.withExperiment().withCode().thatEquals(instrumentCollectionID);
  const fo = new openbis.SampleFetchOptions();
  fo.withType();
  fo.withProperties();
  fo.withPropertiesHistory();
  
  // Properly fetch experiment with its related data
  fo.withExperiment().withProject().withSpace();

  const ao = new openbis.PropertyAssignmentFetchOptions();
  const po = new openbis.PropertyTypeFetchOptions();
  po.withSampleType();
  po.withVocabulary();
  ao.withEntityType();
  ao.withPropertyTypeUsing(po);
  fo.withType().withPropertyAssignmentsUsing(ao);

  const result = await api.searchSamples(sc, fo);
  return result.getObjects();
}

export async function getObject(
  api: openbis.OpenBISJavaScriptFacade,
  code: string,
): Promise<openbis.Sample[]>{
  const sc = new openbis.SampleSearchCriteria();
  sc.withCode().thatEquals(code);
  const fo = new openbis.SampleFetchOptions();
  fo.withType();
  fo.withProperties();
  fo.withPropertiesHistory();
  
  // Properly fetch experiment with its related data
  fo.withExperiment().withProject().withSpace();

  const ao = new openbis.PropertyAssignmentFetchOptions();
  const po = new openbis.PropertyTypeFetchOptions();
  po.withSampleType();
  po.withVocabulary();
  ao.withEntityType();
  ao.withPropertyTypeUsing(po);
  fo.withType().withPropertyAssignmentsUsing(ao);

  const result = await api.searchSamples(sc, fo);
  return result.getObjects();
}

export async function getObjectByPermId(
  api: openbis.OpenBISJavaScriptFacade,
  permId: string,
): Promise<openbis.Sample | null> {
  const sc = new openbis.SampleSearchCriteria();
  sc.withId().thatEquals(new openbis.SamplePermId(permId));
  const fo = new openbis.SampleFetchOptions();
  fo.withType();
  fo.withProperties();

  const result = await api.searchSamples(sc, fo);
  const objects = result.getObjects();
  return objects.length > 0 ? objects[0] : null;
}

/**
 * Create a new object in the iLog inventory Equipment collection.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param type - The object type.
 * @param properties - The object properties.
 * @param spacePermId - The space permission ID.
 * @param projectPermId - The project permission ID.
 * @param collectionPermId - The collection permission ID.
 */
export async function createObject(
  api: openbis.OpenBISJavaScriptFacade,
  type: string,
  properties: object,
  spacePermId: openbis.SpacePermId,
  projectPermId: openbis.ProjectPermId,
  collectionPermId: openbis.ExperimentPermId,
): Promise<void> {
  const newObj = new openbis.SampleCreation();
  newObj.setTypeId(new openbis.EntityTypePermId(type));
  newObj.setAutoGeneratedCode(true);
  newObj.setProperty(iLogID, true);
  newObj.setExperimentId(collectionPermId);
  newObj.setProjectId(projectPermId);
  newObj.setSpaceId(spacePermId);
  for (const [key, value] of Object.entries(properties)) {
    newObj.setProperty(key, value);
  }
  await api.createSamples([newObj]);
}

/**
 * Update an existing object.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param sampleId - The ID of the object to update.
 * @param name - The object updated name.
 */
export async function updateObject(
  api: openbis.OpenBISJavaScriptFacade,
  sampleId: openbis.ISampleId,
  properties: object,
): Promise<void> {
  const updateObj = new openbis.SampleUpdate();
  updateObj.setSampleId(sampleId);
  for (const [key, value] of Object.entries(properties)) {
    if (Array.isArray(value) && value.length === 0) {
      updateObj.setProperty(key, "-");
    } else if (Array.isArray(value) && value.length === 1) {
      updateObj.setProperty(key, value[0]);
    } else if (Array.isArray(value) && value.length > 1) {
      updateObj.setProperty(key, value.join(','));
    } else if (value === "" || value === undefined) {
      updateObj.setProperty(key, "-");
    } else {
      updateObj.setProperty(key, value);
    }
  }
  await api.updateSamples([updateObj]);
}

/**
 * Delete an object.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param sampleId - The ID of the object to delete.
 */
export async function deleteObject(
  api: openbis.OpenBISJavaScriptFacade,
  sampleId: openbis.SamplePermId,
): Promise<void> {
  const sdo = new openbis.SampleDeletionOptions();
  sdo.setReason('Object no longer needed.');
  await api.deleteSamples([sampleId], sdo);
}
