import openbis from "@openbis/openbis.esm";
import { iLogID, labID, componentCollectionID, instrumentCollectionID } from "../shared/common";

// TODO
// 1.Look for templates in the settings
// 2.Export async function createInheritedType(api: openbis.OpenBISJavaScriptFacade, baseType: string, ):
//   Search for a type of type baseType and copy all property assignments into the new type.
//   Use a set to keep the list of assignments to make sure that they are unique between the base type and the derived type
//   Probably we can use some internal field to keep track of the inheritance relationships on the openbis 
//   Maybe we create a very base type in openbis which has some hidden fields that we use to track the inheritance

/**
 * Get all objects from the iLog inventory Equipment collection.
 * @param api - The OpenBIS JavaScript facade instance.
 * @returns A promise that resolves to an array of Sample objects.
 */
export async function getObjects(
  api: openbis.OpenBISJavaScriptFacade,
): Promise<openbis.Sample[]> {
  const sc = new openbis.SampleSearchCriteria();
  sc.withSpace().withCode().thatEquals(labID);
  sc.withProject().withCode().thatEquals(iLogID);
  const experimentCriteria = sc.withSubcriteria().withOrOperator();
  experimentCriteria.withExperiment().withCode().thatEquals(componentCollectionID);
  experimentCriteria.withExperiment().withCode().thatEquals(instrumentCollectionID);
  const fo = new openbis.SampleFetchOptions();
  fo.withType();
  fo.withProperties();
  fo.withPropertiesHistory();
  
  // Properly fetch experiment with its related data
  fo.withExperiment().withProject().withSpace();

  const ao = new openbis.PropertyAssignmentFetchOptions();
  const po = new openbis.PropertyTypeFetchOptions();
  po.withSampleType();
  po.withVocabulary();
  ao.withEntityType();
  ao.withPropertyTypeUsing(po);
  fo.withType().withPropertyAssignmentsUsing(ao);

  const result = await api.searchSamples(sc, fo);
  return result.getObjects();
}

export async function getObject(
  api: openbis.OpenBISJavaScriptFacade,
  code: string,
): Promise<openbis.Sample[]>{
  const sc = new openbis.SampleSearchCriteria();
  sc.withCode().thatEquals(code);
  const fo = new openbis.SampleFetchOptions();
  fo.withType();
  fo.withProperties();
  fo.withPropertiesHistory();
  
  // Properly fetch experiment with its related data
  fo.withExperiment().withProject().withSpace();

  const ao = new openbis.PropertyAssignmentFetchOptions();
  const po = new openbis.PropertyTypeFetchOptions();
  po.withSampleType();
  po.withVocabulary();
  ao.withEntityType();
  ao.withPropertyTypeUsing(po);
  fo.withType().withPropertyAssignmentsUsing(ao);

  const result = await api.searchSamples(sc, fo);
  return result.getObjects();
}

/**
 * Create a new object in the iLog inventory Equipment collection.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param type - The object type.
 * @param name - The object name.
 */
export async function createObject(
  api: openbis.OpenBISJavaScriptFacade,
  type: string,
  properties: object,
  spacePermId: openbis.SpacePermId,
  projectPermId: openbis.ProjectPermId,
  collectionPermId: openbis.ExperimentPermId,
): Promise<void> {
  const newObj = new openbis.SampleCreation();
  newObj.setTypeId(new openbis.EntityTypePermId(type));
  newObj.setAutoGeneratedCode(true);
  newObj.setProperty(iLogID, true);
  newObj.setExperimentId(collectionPermId);
  newObj.setProjectId(projectPermId);
  newObj.setSpaceId(spacePermId);
  for (const [key, value] of Object.entries(properties)) {
    newObj.setProperty(key, value);
  }
  await api.createSamples([newObj]);
}

/**
 * Update an existing object.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param sampleId - The ID of the object to update.
 * @param name - The object updated name.
 */
export async function updateObject(
  api: openbis.OpenBISJavaScriptFacade,
  sampleId: openbis.ISampleId,
  properties: object,
): Promise<void> {
  const updateObj = new openbis.SampleUpdate();
  updateObj.setSampleId(sampleId);
  for (const [key, value] of Object.entries(properties)) {
    if (Array.isArray(value) && value.length === 0) {
      updateObj.setProperty(key, undefined);
    } else if (Array.isArray(value) && value.length === 1) {
      updateObj.setProperty(key, value[0]);
    } else if (Array.isArray(value) && value.length > 1) {
      updateObj.setProperty(key, value.join(','));
    } else {
      updateObj.setProperty(key, value);
    }
  }
  await api.updateSamples([updateObj]);
}

/**
 * Delete an object.
 * @param api - The OpenBIS JavaScript facade instance.
 * @param sampleId - The ID of the object to delete.
 */
export async function deleteObject(
  api: openbis.OpenBISJavaScriptFacade,
  sampleId: openbis.SamplePermId,
): Promise<void> {
  const sdo = new openbis.SampleDeletionOptions();
  sdo.setReason('Object no longer needed.');
  await api.deleteSamples([sampleId], sdo);
}
