/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthObjectsImport } from './routes/_auth.objects'
import { Route as AuthInfoImport } from './routes/_auth.info'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthObjectsRoute = AuthObjectsImport.update({
  path: '/objects',
  getParentRoute: () => AuthRoute,
} as any)

const AuthInfoRoute = AuthInfoImport.update({
  path: '/info',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/info': {
      id: '/_auth/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthInfoImport
      parentRoute: typeof AuthImport
    }
    '/_auth/objects': {
      id: '/_auth/objects'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof AuthObjectsImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({ AuthInfoRoute, AuthObjectsRoute }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/info",
        "/_auth/objects"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/info": {
      "filePath": "_auth.info.tsx",
      "parent": "/_auth"
    },
    "/_auth/objects": {
      "filePath": "_auth.objects.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
