/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthUserinfoImport } from './routes/_auth/user_info'
import { Route as AuthHomeImport } from './routes/_auth/home'
import { Route as AuthTypesIndexImport } from './routes/_auth/types/index'
import { Route as AuthObjectsIndexImport } from './routes/_auth/objects/index'
import { Route as AuthTypesCreatorImport } from './routes/_auth/types/creator'
import { Route as AuthObjectsCreatorImport } from './routes/_auth/objects/creator'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthUserinfoRoute = AuthUserinfoImport.update({
  path: '/user_info',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHomeRoute = AuthHomeImport.update({
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTypesIndexRoute = AuthTypesIndexImport.update({
  path: '/types/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthObjectsIndexRoute = AuthObjectsIndexImport.update({
  path: '/objects/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTypesCreatorRoute = AuthTypesCreatorImport.update({
  path: '/types/creator',
  getParentRoute: () => AuthRoute,
} as any)

const AuthObjectsCreatorRoute = AuthObjectsCreatorImport.update({
  path: '/objects/creator',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/user_info': {
      id: '/_auth/user_info'
      path: '/user_info'
      fullPath: '/user_info'
      preLoaderRoute: typeof AuthUserinfoImport
      parentRoute: typeof AuthImport
    }
    '/_auth/objects/creator': {
      id: '/_auth/objects/creator'
      path: '/objects/creator'
      fullPath: '/objects/creator'
      preLoaderRoute: typeof AuthObjectsCreatorImport
      parentRoute: typeof AuthImport
    }
    '/_auth/types/creator': {
      id: '/_auth/types/creator'
      path: '/types/creator'
      fullPath: '/types/creator'
      preLoaderRoute: typeof AuthTypesCreatorImport
      parentRoute: typeof AuthImport
    }
    '/_auth/objects/': {
      id: '/_auth/objects/'
      path: '/objects'
      fullPath: '/objects'
      preLoaderRoute: typeof AuthObjectsIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/types/': {
      id: '/_auth/types/'
      path: '/types'
      fullPath: '/types'
      preLoaderRoute: typeof AuthTypesIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthHomeRoute: typeof AuthHomeRoute
  AuthUserinfoRoute: typeof AuthUserinfoRoute
  AuthObjectsCreatorRoute: typeof AuthObjectsCreatorRoute
  AuthTypesCreatorRoute: typeof AuthTypesCreatorRoute
  AuthObjectsIndexRoute: typeof AuthObjectsIndexRoute
  AuthTypesIndexRoute: typeof AuthTypesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHomeRoute: AuthHomeRoute,
  AuthUserinfoRoute: AuthUserinfoRoute,
  AuthObjectsCreatorRoute: AuthObjectsCreatorRoute,
  AuthTypesCreatorRoute: AuthTypesCreatorRoute,
  AuthObjectsIndexRoute: AuthObjectsIndexRoute,
  AuthTypesIndexRoute: AuthTypesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof AuthHomeRoute
  '/user_info': typeof AuthUserinfoRoute
  '/objects/creator': typeof AuthObjectsCreatorRoute
  '/types/creator': typeof AuthTypesCreatorRoute
  '/objects': typeof AuthObjectsIndexRoute
  '/types': typeof AuthTypesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof AuthHomeRoute
  '/user_info': typeof AuthUserinfoRoute
  '/objects/creator': typeof AuthObjectsCreatorRoute
  '/types/creator': typeof AuthTypesCreatorRoute
  '/objects': typeof AuthObjectsIndexRoute
  '/types': typeof AuthTypesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/user_info': typeof AuthUserinfoRoute
  '/_auth/objects/creator': typeof AuthObjectsCreatorRoute
  '/_auth/types/creator': typeof AuthTypesCreatorRoute
  '/_auth/objects/': typeof AuthObjectsIndexRoute
  '/_auth/types/': typeof AuthTypesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/user_info'
    | '/objects/creator'
    | '/types/creator'
    | '/objects'
    | '/types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/user_info'
    | '/objects/creator'
    | '/types/creator'
    | '/objects'
    | '/types'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/home'
    | '/_auth/user_info'
    | '/_auth/objects/creator'
    | '/_auth/types/creator'
    | '/_auth/objects/'
    | '/_auth/types/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/home",
        "/_auth/user_info",
        "/_auth/objects/creator",
        "/_auth/types/creator",
        "/_auth/objects/",
        "/_auth/types/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/home": {
      "filePath": "_auth/home.tsx",
      "parent": "/_auth"
    },
    "/_auth/user_info": {
      "filePath": "_auth/user_info.tsx",
      "parent": "/_auth"
    },
    "/_auth/objects/creator": {
      "filePath": "_auth/objects/creator.tsx",
      "parent": "/_auth"
    },
    "/_auth/types/creator": {
      "filePath": "_auth/types/creator.tsx",
      "parent": "/_auth"
    },
    "/_auth/objects/": {
      "filePath": "_auth/objects/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/types/": {
      "filePath": "_auth/types/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
